### ISSUE TITLE
Value Filter doesn't work

### ISSUE THREAD

**Issue by janantala** [sematext/spm-metrics-js#1]
All values are sent when I set `valueFilter: ['count', 'currentRate']` to only specified fields.
The problem should be here https://github.com/sematext/spm-metrics-js/blob/316321d1e8cce07e83d11319dfeb03f0a05d07e1/lib/customMetric.js#L71

**Comment by megastef** [comment]
Hi @janantala, thanks for reporting the issue. Changed, plus test in  commit https://github.com/sematext/spm-metrics-js/commit/3288ea7267a54318e6ce7911b6ef7f1cd2b5594b.  Please update with `npm i spm-metrics-js@1.0.12 --save`
